spring:
  application:
    name: portal-motorista-api

  # ==============================================================
  # Propriedades do PostgresSQL
  # ==============================================================
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  # ==============================================================
  # Propriedades do JPA
  # ==============================================================
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        default_schema: public

  # ==============================================================
  # Propriedades do Flyway
  # ==============================================================
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

  # ==============================================================
  # Multipart/Upload
  # ==============================================================
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# ==============================================================
# Configuração do Servidor
# ==============================================================
server:
  servlet:
    context-path: /api

# ==============================================================
# Propriedades do JWT
# ==============================================================
jwt:
  time:
    minutes:
      exp: 1440
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

# ==============================================================
# Swagger/SpringDoc
# ==============================================================
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /docs

